# Generated by Django 5.2.10 on 2026-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for alarm scheduling", max_length=50),
        ),
    ]
