# Generated by Django 5.2.10 on 2026-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alarm_enabled',
            field=models.BooleanField(default=False, help_text='Whether to send alarm reminders'),
        ),
        migrations.AddField(
            model_name='task',
            name='alarm_minutes_before',
            field=models.PositiveIntegerField(default=15, help_text='Minutes before due time to send alarm'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True, help_text='Time of day when task is due', null=True),
        ),
    ]
