# Generated by Django 5.2.10 on 2026-02-12 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_task_alarm_enabled_task_alarm_minutes_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcompletion',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
