services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A api worker --loglevel=info
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A api beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis_data:
