FROM ghcr.io/astral-sh/uv:latest AS uv_bin

FROM python:3.14-alpine
COPY --from=uv_bin /uv /uvx /bin/
RUN apk add --no-cache gcc musl-dev linux-headers
WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
RUN uv pip install --system .
ENV PYTHONPATH=/app
USER guest
