apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: tons/rutineret
deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - name: rutineret
        chartPath: charts/rutineret
        namespace: rutineret
        createNamespace: true
        setValueTemplates:
          googleOAuth:
            clientId: "{{.GOOGLE_OAUTH2_CLIENT_ID}}"
            clientSecret: "{{.GOOGLE_OAUTH2_CLIENT_SECRET}}"
          frontendUrl: "{{.FRONTEND_URL}}"
          apiUrl: "{{.API_URL}}"
          ingress:
            enabled: true
            hosts:
              - host: "{{.HOST}}"
                paths:
                  - path: /
                    pathType: ImplementationSpecific
