apiVersion: skaffold/v4beta13
kind: Config
build:
  artifacts:
    - image: tons/rutineret
deploy:
  statusCheckDeadlineSeconds: 300
  tolerateFailuresUntilDeadline: true
  helm:
    releases:
      - name: rutineret
        chartPath: charts/rutineret
        namespace: "rutineret-{{ .CLASSIFICATION }}"
        createNamespace: true
        upgradeOnChange: true
        useHelmSecrets: true
        valuesFiles:
          - charts/rutineret/data/secrets/{{ .CLASSIFICATION }}.yaml
        setValueTemplates:
          frontendUrl: "{{.FRONTEND_URL}}"
          apiUrl: "{{.API_URL}}"
          ingress:
            enabled: true
            hosts:
              - host: "{{.HOST}}"
                paths:
                  - path: /
                    pathType: ImplementationSpecific

profiles:
  - name: always-pull
    deploy:
      helm:
        releases:
          - name: rutineret
            setValueTemplates:
              image:
                pullPolicy: Always
