{{- if not .Values.valkeyConnection.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rutineret.fullname" . }}
  labels:
    {{- include "rutineret.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.valkeyConnection.password | b64enc | quote }}
{{- end }}
